### ISSUE TITLE
Make it easier to recover incorrectly-formatted commit messages

### ISSUE THREAD

**Issue by kalekundert** [jeremyagray/pccc#1]
When used as a `commit-msg` hook, `pccc` does not make it easy to recover a commit message (particularly a long one entered via the editor) that don't match the conventional commit format (perhaps due to a small typo like "doc: ..." instead of "docs: ...").  The message is not copied to stdout, and AFAIK git does not provide a command to edit a message that fails the `commit-msg` hook.  (Although the most recent commit message is saved to `.git/COMMIT_EDITMSG`, so you can manually recover it if you know to look there.)

The easiest way to address this issue would be to simply print the whole commit message to stdout after detecting a formatting error.  Beyond that, I think it would be nice for there to be a command-line/config option that would allow the user to continue editing the message until it matches the expected format.  Perhaps something like `--on-failure=<print|edit>`.  Let me know if there's interest in this, and I can try to put a PR together.

For completeness, here is the `commit-msg` hook I use:
```
# .git/hooks/commit-msg
pccc $1
```
Here is an alias that can be used to edit the most recent commit message (which alleviates this issue):
```
gce='git commit -F $(git root)/.git/COMMIT_EDITMSG -e'
```

**Comment by jeremyagray** [comment]
I added mirroring the commit message to standard output on failure by default and pushed out 0.4.2 after I fixed a `sys.stdout` and `sys.stderr` problem and some broken tests.

Originally I had planned an elaborate interactive error handling and reformatting process, but since all the tooling uses the exit status and magit keeps a copy of the message in its commit message ring anyway, the original plan was scrapped.  The current plan is to mirror bad messages to standard output (done) and later, it will output reformatted messages to standard output.  This may change at some point to output errors and the bad message to standard error and the reformatted message to standard output.

It may still be easier to use a commit message file for editing on failure or to let the editor (or IDE) keep a copy (like magit's message ring).
